# Generated by Django 3.0.3 on 2020-03-04 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0002_topic_owner'),
        ('entries', '0002_auto_20200226_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_list', to='topics.Topic'),
        ),
    ]
